version: '3.3'

services:
  autotest:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${autotest_results}:/app/autotest-results
      - ${allure_results}:/app/allure-results
      - ${localtime}:/etc/localtime:ro
    env_file:
      - ./.env

volumes:
  autotest-results:
  allure-results:
  localtime: